# RotorWise AI Deployment Configuration for Render

services:
  - type: web
    name: rotorwise-ai
    env: static
    staticPublishPath: "./"
    envVars:
      - key: API_KEY
        sync: false  # Set manually in Render dashboard

    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
