# render.yaml
# This file configures the deployment of the RotorWise AI application on Render.

services:
  - type: static_site # Corrected service type for a static site.
    name: rotorwise-ai # A name for the service.
    # The build command finds the placeholder __GEMINI_API_KEY__ in index.html
    # and replaces it with the actual API_KEY from the environment variables.
    buildCommand: "sed -i 's|__GEMINI_API_KEY__|'\"$API_KEY\"'|g' index.html"
    # The root directory contains index.html and all other static assets to be served.
    publishDir: "."
    envVars:
      # IMPORTANT: You must set the API_KEY in the Render dashboard under Environment.
      - key: API_KEY
    headers:
      # Prevents aggressive caching to ensure users get the latest version of the app.
      - path: "/*"
        name: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"
