# RotorWise AI Deployment Configuration for Render

services:
  - type: web
    name: rotorwise-ai
    env: static
    buildCommand: >
      node -e "let f = 'index.html'; require('fs').writeFileSync(f, require('fs').readFileSync(f, 'utf8').replace('__GEMINI_API_KEY__', process.env.API_KEY))"
    staticPublishPath: "./"
    envVars:
      - key: API_KEY
        sync: false  # Set manually in Render dashboard

    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "no-cache, no-store, must-revalidate"