# Exported from Render on 2025-10-17T07:34:25Z
version: "1"
services:
- type: web
  name: rotorwiseAI
  runtime: node
  repo: https://github.com/lukeponga-dev/rotorwiseAI
  plan: free
  region: oregon
  buildCommand: npm install; npm build
  startCommand: npm run dev
  autoDeployTrigger: commit
